-- MySQL Script generated by MySQL Workbench
-- Sat Apr 20 11:29:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `idSede` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idSede`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `NombreUsuario` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `FechaCreacion` VARCHAR(45) NULL,
  `Contrasena` VARCHAR(45) NULL,
  `Tipo_usuario_idTipo_usuario` INT NOT NULL,
  `Sede_idSede` INT NOT NULL,
  `Foto` BLOB NULL,
  `Nombres` VARCHAR(45) NULL,
  `Apellidos` VARCHAR(45) NULL,
  `DNI` VARCHAR(8) NULL,
  `Correo` VARCHAR(45) NULL,
  `Distrito` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Sede1_idx` (`Sede_idSede` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Sede1`
    FOREIGN KEY (`Sede_idSede`)
    REFERENCES `mydb`.`Sede` (`idSede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamentos` (
  `idMedicamentos` INT NOT NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Foto` BLOB NULL,
  `Inventario` VARCHAR(45) NULL,
  `Precio_unidad` VARCHAR(45) NULL,
  `Fecha_ingreso` DATETIME NULL,
  PRIMARY KEY (`idMedicamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Proveedorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Envios` (
  `idEnvios` INT NOT NULL,
  `Descripcion` VARCHAR(250) NULL,
  `FechaRegistro` DATETIME NULL,
  `FechaEntrega` DATETIME NULL,
  `Estado` VARCHAR(45) NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idEnvios`),
  INDEX `fk_Envios_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Envios_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medicamentos_has_Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medicamentos_has_Envios` (
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `Pedidos_idPedidos` INT NOT NULL,
  PRIMARY KEY (`Medicamentos_idMedicamentos`, `Pedidos_idPedidos`),
  INDEX `fk_Medicamentos_has_Pedidos_Pedidos1_idx` (`Pedidos_idPedidos` ASC) VISIBLE,
  INDEX `fk_Medicamentos_has_Pedidos_Medicamentos1_idx` (`Medicamentos_idMedicamentos` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamentos_has_Pedidos_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `mydb`.`Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Medicamentos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`Pedidos_idPedidos`)
    REFERENCES `mydb`.`Envios` (`idEnvios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `idMedico` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Sede_idSede` INT NOT NULL,
  `ColegiaturaMedico` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedico`),
  INDEX `fk_Medico_Sede1_idx` (`Sede_idSede` ASC) VISIBLE,
  CONSTRAINT `fk_Medico_Sede1`
    FOREIGN KEY (`Sede_idSede`)
    REFERENCES `mydb`.`Sede` (`idSede`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL,
  `FechaSolicitud` DATETIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Costo_total` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Tipo` VARCHAR(45) NULL,
  `Receta` BLOB NULL,
  `FechaEntrega` DATETIME NULL,
  `Comentario` VARCHAR(45) NULL,
  `IndicadorReceta` VARCHAR(45) NULL,
  `MetodoPago` VARCHAR(45) NULL,
  `FechaAprobacion` DATETIME NULL,
  `Tracking` VARCHAR(45) NULL,
  `Medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idVentas`, `Usuario_idUsuario`, `Medico_idMedico`),
  INDEX `fk_Ventas_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Ventas_Medico1_idx` (`Medico_idMedico` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Medico1`
    FOREIGN KEY (`Medico_idMedico`)
    REFERENCES `mydb`.`Medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas_has_Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas_has_Medicamentos` (
  `Ventas_idVentas` INT NOT NULL,
  `Medicamentos_idMedicamentos` INT NOT NULL,
  `Cantidad` VARCHAR(45) NULL,
  `Costo_por_medicamento` VARCHAR(45) NULL,
  PRIMARY KEY (`Ventas_idVentas`, `Medicamentos_idMedicamentos`),
  INDEX `fk_Ventas_has_Medicamentos_Medicamentos1_idx` (`Medicamentos_idMedicamentos` ASC) VISIBLE,
  INDEX `fk_Ventas_has_Medicamentos_Ventas1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_has_Medicamentos_Ventas1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `mydb`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_has_Medicamentos_Medicamentos1`
    FOREIGN KEY (`Medicamentos_idMedicamentos`)
    REFERENCES `mydb`.`Medicamentos` (`idMedicamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Solicitudes` (
  `idSolicitudes` INT NOT NULL,
  `FechaSolicitud` DATETIME NULL,
  `Estado` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(250) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idSolicitudes`, `Usuario_idUsuario`),
  INDEX `fk_Solicitudes_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitudes_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `Seguro` VARCHAR(45) NULL,
  `Edad` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`, `Usuario_idUsuario`),
  INDEX `fk_Paciente_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Paciente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta` (
  `idTarjeta` INT NOT NULL,
  `Numero` VARCHAR(45) NULL,
  `FechaCaduca` VARCHAR(45) NULL,
  `CCI` VARCHAR(45) NULL,
  PRIMARY KEY (`idTarjeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoDeEnvio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstadoDeEnvio` (
  `idEstado` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  `Envios_idEnvios` INT NOT NULL,
  PRIMARY KEY (`idEstado`, `Envios_idEnvios`),
  INDEX `fk_EstadoDeEnvio_Envios1_idx` (`Envios_idEnvios` ASC) VISIBLE,
  CONSTRAINT `fk_EstadoDeEnvio_Envios1`
    FOREIGN KEY (`Envios_idEnvios`)
    REFERENCES `mydb`.`Envios` (`idEnvios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles` (
  `idRoles` INT NOT NULL,
  `Paciente` INT NOT NULL,
  `AdminSede` INT NOT NULL,
  `SuperAdmin` INT NOT NULL,
  `Farmacista` INT NOT NULL,
  PRIMARY KEY (`idRoles`, `Paciente`, `AdminSede`, `SuperAdmin`, `Farmacista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Roles_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Roles_has_Usuario` (
  `Roles_idRoles` INT NOT NULL,
  `Roles_Paciente` INT NOT NULL,
  `Roles_Admin` INT NOT NULL,
  `Roles_SuperAdmin` INT NOT NULL,
  `Roles_Farmacista` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`Roles_idRoles`, `Roles_Paciente`, `Roles_Admin`, `Roles_SuperAdmin`, `Roles_Farmacista`, `Usuario_idUsuario`),
  INDEX `fk_Roles_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Roles_has_Usuario_Roles1_idx` (`Roles_idRoles` ASC, `Roles_Paciente` ASC, `Roles_Admin` ASC, `Roles_SuperAdmin` ASC, `Roles_Farmacista` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_has_Usuario_Roles1`
    FOREIGN KEY (`Roles_idRoles` , `Roles_Paciente` , `Roles_Admin` , `Roles_SuperAdmin` , `Roles_Farmacista`)
    REFERENCES `mydb`.`Roles` (`idRoles` , `Paciente` , `AdminSede` , `SuperAdmin` , `Farmacista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
